### PR TITLE
Vaccine Equity: Team1 Deliverable1

### PR DESCRIPTION
**Pull request by b-tao**

### CODE REVIEW

**Comment by 97harsh** [comment]
Please tag me and Leo if you want to have this merged

**Comment by b-tao** [comment]
Hi, I'm not sure if we actually have to merge our deliverables to the main repo. I thought we just needed to create a pull request with the Deliverable to submit them for CS506.

**Comment by 97harsh** [comment]
If you do not merge these changes, the successive changes wouldn't reflect in the dev branch.

**Comment by b-tao** [comment]
I see, thank you. Yes, @97harsh @leoseoane1 I would like this PR with our Deliverable 1 to be merged.

**Review by 97harsh — APPROVED** [review]

**Pull request merged**
