### PR TITLE
deliverable 4

### PR DESCRIPTION
**Pull request by lelandling**
consolidated hypothesis testing - consolidated for both roc and cumulative percent data plot feature ipynb contains all datavis + arima test (which nothing came out of it) final report draft contains most content, need to finish last part.

### CODE REVIEW

**Comment by lelandling** [comment]
@97harsh @leoseoane1 @mvoong18

**Comment by lelandling** [comment]
@mvoong18  @97harsh  @leoseoane1

**Comment by lelandling** [comment]
also something to note is we had to submit a draft to gradescope -- gradescope draft is behind the draft uploaded here

**Comment by 97harsh** [comment]
please raise re-request to merge it to dev branch, where final codes and documentation will remain

**Pull request closed without merging**
